lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600                                            # durée de validité du token en secondes
    user_identity_field: email                                 # le champ de l'utilisateur utilisé pour l'authentification
