controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login_check:
    path: /api/login_check
reset_password:
    path: /api/reset-password/{token}
    controller: App\Controller\Api\ResetPasswordController::resetPassword
    methods: [POST]
