controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login_check:
    path: /api/login_check
reset_password:
    path: /api/reset-password/{token}
    controller: App\Controller\Api\ResetPasswordController::resetPassword
    methods: [POST]
file_upload:
    path: /api/upload
    controller: App\Controller\Api\UploadFileController::upload
    methods: [POST]
api_appel_offres_create:
    path: '/api/create/appel-offres'
    controller: 'App\Controller\Api\AppelOffreController::create'
    methods: ['POST']

api_appel_offres_get:
    path: '/api/get/appel-offres/{id}'
    controller: 'App\Controller\Api\AppelOffreController::getOne'
    methods: ['GET']

api_appel_offres_get_by_name:
    path: '/api/getOne/appel-offres/{id}'
    controller: 'App\Controller\Api\AppelOffreController::getOneByName'
    methods: ['GET']

api_appel_offres_update:
    path: '/api/put/appel-offres/{id}'
    controller: 'App\Controller\Api\AppelOffreController::update'
    methods: ['PUT']

api_appel_offres_delete:
    path: '/api/delete/appel-offres/{id}'
    controller: 'App\Controller\Api\AppelOffreController::delete'
    methods: ['DELETE']

api_appel_offres_index:
    path: '/api/getAll/appelOffres'
    controller: 'App\Controller\Api\AppelOffreController::index'
    methods: ['GET']
api_employe_create:
    path: '/api/create/employe'
    controller: 'App\Controller\Api\EmployeController::create'
    methods: ['POST']

api_employe_get_all:
    path: '/api/getAll/employes'
    controller: 'App\Controller\Api\EmployeController::getAll'
    methods: ['GET']

api_employe_update:
    path: '/api/put/employe/{id}'
    controller: 'App\Controller\Api\EmployeController::update'
    methods: ['PUT']

api_employe_delete:
    path: '/api/delete/employe/{id}'
    controller: 'App\Controller\Api\EmployeController::delete'
    methods: ['DELETE']

api_employe_get_one:
    path: '/api/get/employe/{id}'
    controller: 'App\Controller\Api\EmployeController::getOne'
    methods: ['GET']

api_employe_get_one_by_name:
    path: '/api/getOne/employe/{id}'
    controller: 'App\Controller\Api\EmployeController::getOneByNOM'
    methods: ['GET']

api_projet_create:
  path: /api/create/projet
  controller: 'App\Controller\Api\ProjetController::create'
  methods: [POST]

api_projet_get_all:
  path: /api/getAll/projets
  methods: [GET]
  controller: 'App\Controller\Api\ProjetController::getAll'

api_projet_get_one:
  path: /api/get/projet/{id}
  methods: [GET]
  controller: 'App\Controller\Api\ProjetController::getProjetDetails'

api_projet_get_one_by_id:
  path: /api/getOne/projet/{id}
  methods: [GET]
  controller: 'App\Controller\Api\ProjetController::getProjetOne'

api_projet_delete:
  path: /api/delete/projet/{id}
  methods: [DELETE]
  controller: 'App\Controller\Api\ProjetController::delete'

api_projet_update:
  path: /api/update/projet/{id}
  methods: [PUT]
  controller: 'App\Controller\Api\ProjetController::update'
api_projet-employe-poste_get:
    path: '/api/getAll/projet-employe-poste'
    controller: 'App\Controller\Api\ProjetEmployePosteController::index'
    methods: ['GET']

api_projet-employe-poste_get_one:
    path: '/api/getOne/projet-employe-poste/{id}'
    controller: 'App\Controller\Api\ProjetEmployePosteController::getOne'
    methods: ['GET']

api_projet-employe-poste_create:
    path: '/api/create/projet-employe-poste'
    controller: 'App\Controller\Api\ProjetEmployePosteController::create'
    methods: ['POST']

api_projet-employe-poste_update:
    path: '/api/put/projet-employe-poste/{id}'
    controller: 'App\Controller\Api\ProjetEmployePosteController::update'
    methods: ['PUT']

api_projet-employe-poste_delete:
    path: '/api/delete/projet-employe-poste/{id}'
    controller: 'App\Controller\Api\ProjetEmployePosteController::delete'
    methods: ['DELETE']
