parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    # default configuration for services in *this* file
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle: ~
    App\Controller\Api\UserController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $userRepository: '@App\Repository\UserRepository'
            $passwordHasher: '@security.user_password_hasher'
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualifiead class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Command\CreateAdminUserCommand:
        tags:
            - { name: 'console.command' }php bin/console app:create-admin-user
